apiVersion: v1
kind: Service
metadata:
  name: nodeapp-load-balancer-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: voting-app
    type: front-end
